app:
  oauth2:
    base-url: http://localhost:9080
    realm: keycloak

server:
  error:
    whitelabel:
      enabled: false

frontend:
  urls: {}

spring:
  application:
    name: Pluto
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://jaeger-collector.jaeger:9411/

security:
  oidc:
    auth-uri: ${app.oauth2.base-url}/auth/realms/${app.oauth2.realm}/protocol/openid-connect/auth
    logout-uri: ${app.oauth2.base-url}/auth/realms/${app.oauth2.realm}/protocol/openid-connect/logout?redirect_uri=%s
    token-uri: ${app.oauth2.base-url}/auth/realms/${app.oauth2.realm}/protocol/openid-connect/token
    jwk-key-set-uri: ${app.oauth2.base-url}/auth/realms/${app.oauth2.realm}/protocol/openid-connect/certs
    redirect-after-logout-uri: https://fairspace.com
    clientId: web_app
    clientSecret: web_app
    scope: openid
    required-authority: user-workspace

  # Specify urls for security configuration. There are
  urls:
    permitAll:
    - /actuator/health
    - /error
    - /manifest.json
    - /login
    - /logout
    - /authorize
    - /account/tokens
    needsAuthentication:
    - /account/name
    - /*
    needsAuthorization:
    - /account/authorizations
    - /api/*

workspace:
  name: Workspace
  version: 0.0.0

keycloak:
  workspace-login-group: workspace-users
  groupUri: ${app.oauth2.base-url}/auth/admin/realms/${app.oauth2.realm}/groups/?max=1&search=${keycloak.workspace-login-group}

  # The URI pattern has 2 parameters: the groupId and a query string
  usersUriPattern: ${app.oauth2.base-url}/auth/admin/realms/${app.oauth2.realm}/groups/%s/members?%s

zuul:
  routes:
    storage:
      # The webdav URL is not only used in the request URI, but also in headers (e.g. Destination)
      # To avoid rewriting these headers, it is suggested that the path on the proxy is the same
      # as the path on the upstream service for webdav calls.
      path: /webdav/**
      url: http://saturn/
      strip-prefix: false
    metadata:
      path: /api/metadata/**
      url: http://saturn/api/metadata/
    vocabulary:
      path: /api/vocabulary/**
      url: http://saturn/api/vocabulary/
    collections:
      path: /api/collections/**
      url: http://saturn/api/collections/
    permissions:
      path: /api/permissions/**
      url: http://saturn/api/permissions/
    ui:
      path: /**
      url: http://mercury/
    notebooks:
      path: /api/notebooks/**
      url: http://jupyterhub/
    elasticsearch:
      path: /api/search/*/_search
      url: http://elasticsearch/
  ignored-patterns:
  - /actuator/**
  - /account/**
  - /api/workspace/**
  - /login
  - /logout
  - /authorize
  - /error
  add-host-header: true
  ignored-headers:
    - Access-Control-Allow-Credentials
    - Access-Control-Allow-Origin
    - Pragma
    - X-Frame-Options
    - X-Content-Type-Options
    - X-XSS-Protection
