{{- $ingress := .Values.fairspace.ingress -}}
{{- if $ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fairspace.name" . }}-pluto-ingress
{{- with $ingress.annotations.pluto }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app: {{ template "fairspace.name" . }}
    chart: {{ template "fairspace.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
{{- if $ingress.tls.enabled }}
  tls:
    - hosts:
      - {{ template "pluto.hostname" $ }}
      secretName: {{ template "fairspace.tlsSecretName" $ }}
{{- end }}
  rules:
    - host: {{ template "pluto.hostname" $ }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Release.Name }}-pluto
              servicePort: 80
  {{- end -}}
