{{- $ingress := .Values.workspace.ingress -}}
{{- if $ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "workspace.name" . }}-mercury-ingress
{{- with $ingress.annotations.mercury }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app: {{ template "workspace.name" . }}
    chart: {{ template "workspace.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
{{- if $ingress.tls.enabled }}
  tls:
    - hosts:
      - {{ template "mercury.hostname" $ }}
      secretName: {{ template "workspace.tlsSecretName" $ }}
{{- end }}
  rules:
    - host: {{ template "mercury.hostname" $ }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Release.Name }}-mercury
              servicePort: 80
{{- end -}}




