# Default values for vre.
# This is a YAML-formatted file.

# The fairspace container images are in a private repository
# See https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
# on how to store and specify the credentials for it
imagePullSecrets: {}

# Set specific workspace name. Defaults to release name
# Please note that if this is set, also set it for pluto in `pluto.workspace.name`
nameOverride:

# Hyperspace that this workspace is connected to
# Please note that pluto also has to know about the
# keycloak baseUrl and realm, see the pluto configuration
hyperspace:
    tls: true
    domain:
    locationOverrides:
        keycloak:

    # TODO: determine better way to handle keycloak credentials
    # Keycloak credentials are needed to setup the workspace (e.g. users, clients)
    # in keycloak. Please note that this is not a sustainable way of doing, due
    # to the sensitive nature of these parameters
    #
    # We could either:
    # - have the hyperspace setup keycloak itself, when creating a new workspace
    # - use temporary credentials for setting up these users
    # - ...
    keycloak:
        username:
        password:
        loginRealm: master
        realm:
        clientSecret:

# Setup ingress for workspace components
workspace:
    ingress:
        enabled: true
        domain:
        annotations:
          pluto:
            kubernetes.io/ingress.class: nginx
          storage:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/proxy-body-size: 10g
            nginx.ingress.kubernetes.io/rewrite-target: /zuul
          jupyter:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/proxy-body-size: 10g
        tls:
            enabled: true
            secretNameOverride:
            certificate:
                obtain: true
                issuerRef:
                    name: letsencrypt-prod
                    kind: ClusterIssuer
                dns01Provider: clouddns

    testuser:
        password: fairspace123
    coordinator:
        password: fairspace123

    # Scripts for setting up keycloak for a workspace
    configurationScripts:
      keycloak:
        enabled: true
        image: fairspace.azurecr.io/fairspace/keycloak-configuration:0.1.1
        pullPolicy: IfNotPresent
    enableExperimentalFeatures: false

# Generic settings for tracing
tracing:
  enabled: true
  samplingRate: 0.1
  baseUrl: http://jaeger-collector.jaeger:9411

services:
  jupyterhub:

#####################################################################
# Specific settings for Pluto subchart
# Default configuration points to mercury and saturn
# in the same workspace
#####################################################################
pluto:
  replicaCount: 1
  rollingUpdate:
    maxUnavailable: 25%
    maxSurge: 25%
  image:
    image: fairspace.azurecr.io/fairspace/pluto
    tag: RELEASEVERSION
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    externalPort: 80
    internalPort: 8080
  resources:
    limits:
      cpu: 1
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 192Mi
  probePath: /actuator/health
  livenessProbe:
    initialDelaySeconds: 20
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  readinessProbe:
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  terminationGracePeriodSeconds: 10

  # Reference to the workspace for informational purposes
  # These values default to the release name and chart version
  # The name is also used in the default setting for requiredAuthority and clientId
  workspace:
    name:
    version: 0.0.0-RELEASEVERSION

  # Keycloak configuration for authentication
  keycloak:
    client:
      id:
      secret:
    redirectAfterLogoutUrl: https://fairspace.com
    requiredAuthority:

  # Where to find the backends for this proxy
  backends:
    ui:
    metadata:
    storage:
    collections:

#####################################################################
# Specific settings for Saturn subchart
#####################################################################
saturn:
  replicaCount: 1
  rollingUpdate:
    maxSurge: 0%
    maxUnavailable: 100%
  image:
    image: fairspace.azurecr.io/fairspace/saturn
    tag: RELEASEVERSION
    pullPolicy: IfNotPresent

  service:
    name: saturn
    type: ClusterIP
    externalPort: 80
    internalPort: 8080

  resources:
    limits:
      cpu: 1
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi

  probePath: /api/health/
  livenessProbe:
    initialDelaySeconds: 20
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  readinessProbe:
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  terminationGracePeriodSeconds: 10

  ## Persist data to a persistent volume
  persistence:
    database:
      enabled: true

      ## A manually managed Persistent Volume and Claim
      ## Requires persistence.enabled: true
      ## If defined, PVC must be created manually before volume will be bound
      # existingClaim:

      ## database data Persistent Volume Storage Class
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
      ##   GKE, AWS & OpenStack)
      ##
      # storageClass: "-"
      accessMode: ReadWriteOnce
      size: 512Mi
      mountPath: /data
    files:
      enabled: true

      ## A manually managed Persistent Volume and Claim
      ## Requires persistence.enabled: true
      ## If defined, PVC must be created manually before volume will be bound
      # existingClaim:

      ## database data Persistent Volume Storage Class
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
      ##   GKE, AWS & OpenStack)
      ##
      # storageClass: "-"
      accessMode: ReadWriteOnce
      size: 512Mi
      mountPath: /data

#####################################################################
# Specific settings for Mercury subchart
#####################################################################
mercury:
  replicaCount: 1
  image:
    image: fairspace.azurecr.io/fairspace/mercury
    tag: RELEASEVERSION
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    externalPort: 80
    internalPort: 80
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
  probePath: /
  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  readinessProbe:
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  terminationGracePeriodSeconds: 10

  urls:
    storage:

#####################################################################
# Specific settings for JupyterHub subchart
#####################################################################
jupyterhub:
  auth:
    type: custom
    custom:
      className: oauthenticator.openid.OpenIDConnectOAuthenticator
      config:
        enable_auth_state: True
        client_id:
        client_secret:
        openid_url:
        session_url:
    scopes:
      - offline_access
  singleuser:
    image:
      name: fairspace.azurecr.io/fairspace/jupyterhub-singleuser
      tag: RELEASEVERSION
    defaultUrl: "/lab"
    extraEnv:
      WORKSPACE_URL:
  hub:
    image:
      name: fairspace.azurecr.io/fairspace/jupyterhub-hub
      tag: RELEASEVERSION
    ingress:
      enabled: false
    extraEnv:
      JUPYTERHUB_CRYPT_KEY:
    extraConfig:
      customConfig: |
        c.KubeSpawner.cmd = ['/start']
        c.KubeSpawner.singleuser_privileged = True
        c.Authenticator.auto_login = True
  proxy:
    # The JupyterHub chart requires this value to be set here with the same
    # length as the actual values
    # Ensure to override this value with a 64-character hex string when installing
    secretToken: "0000000000000000000000000000000000000000000000000000000000000000"

# Pod annotations should remain empty. They are filled within the build process
podAnnotations: {}
