# Default values for vre.
# This is a YAML-formatted file.

# The fairspace container images are in a private repository
# See https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
# on how to store and specify the credentials for it
imagePullSecrets: {}

# Set specific fairspace name. Defaults to release name
nameOverride:

# External dependencies for running the fairspace
external:
  # TODO: determine better way to handle keycloak credentials
  # Keycloak credentials are needed to setup the fairspace (e.g. users, clients)
  # in keycloak. Please note that this is not a sustainable way of doing, due
  # to the sensitive nature of these parameters
  #
  # We could either:
  # - have the hyperspace setup keycloak itself, when creating a new fairspace
  # - use temporary credentials for setting up these users
  # - ...
  keycloak:
    baseUrl:
    username:
    password:
    loginRealm: master
    realm:
    clientSecret:
    serviceAccount:
      username: fairspace-service-account
      password:

  elasticsearch:
    enabled: true
    rest:
      scheme: http
      host:
      port: 9200
    transport:
      host:
      port: 9300

#####################################################################
# Specific settings for ElasticSearch
#####################################################################
elasticsearch:
  enabled: true
  persistence:
    enabled: true
    size: 20Gi
    storageClass: standard
  client:
    resources:
      requests:
        memory: "800Mi"
        cpu: 0.1
      limits:
        memory: "1024Mi"
        cpu: 1
    initResources:
      limits:
        cpu: "25m"
        memory: "128Mi"
      requests:
        cpu: "25m"
        memory: "128Mi"
  data:
    exposeHttp: true
    resources:
      requests:
        memory: "1600Mi"
        cpu: 0.1
      limits:
        memory: "2048Mi"
        cpu: 1
    initResources:
      limits:
        cpu: "25m"
        memory: "128Mi"
      requests:
        cpu: "25m"
        memory: "128Mi"
  master:
    resources:
      requests:
        memory: "800Mi"
        cpu: 0.1
      limits:
        memory: "1024Mi"
        cpu: 1
    initResources:
      limits:
        cpu: "25m"
        memory: "128Mi"
      requests:
        cpu: "25m"
        memory: "128Mi"

# Setup ingress for fairspace components
fairspace:
    name: "fairspace"
    description: "Fairspace"
    ingress:
        enabled: true
        domain:
        annotations:
          saturn:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/proxy-body-size: 10g
          docs:
            kubernetes.io/ingress.class: nginx
        tls:
            enabled: true
            secretNameOverride:
            certificate:
                obtain: true
                issuerRef:
                    name: letsencrypt-prod
                    kind: ClusterIssuer
    keycloak:
      # Roles defining the keycloak roles for this fairspace
      roles:
        user:
        coordinator:
        datasteward:
        sparql:

      # Groups to retrieve a list of users from
      groups:
        user:

    # Scripts for setting up keycloak for a fairspace
    configurationScripts:
      keycloak:
        enabled: true
        dockerRepository: eu.gcr.io
        image: fairspace-207108/keycloak-configuration
        configurationScriptsTag: 0.1.8
        pullPolicy: IfNotPresent
        resources:
            requests:
                cpu: "50m"
                memory: "512Mi"
            limits:
                cpu: "500m"
                memory: "2048Mi"

    enableExperimentalFeatures: false

# Generic settings for tracing
tracing:
  enabled: false
  samplingRate: 0.1
  baseUrl: http://jaeger-collector.jaeger:9411

services:
  jupyterhub:
  cbioportal:

#####################################################################
# Specific settings for Saturn subchart
#####################################################################
saturn:
  auth:
    enableBasicAuth: true
  persistence:
    files:
      ## A manually managed Persistent Volume and Claim
      ## If defined, PVC must be created manually before volume will be bound
      # existingClaim:

      ## database data Persistent Volume Storage Class
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
      ##   GKE, AWS & OpenStack)
      ##
      # storageClass: "-"
      size: 50Gi
    database:
      size: 50Gi
  image:
    image: eu.gcr.io/fairspace-207108/projects
    tag: RELEASEVERSION
    pullPolicy: IfNotPresent
  initContainer:
    image: alpine:3.9
    pullPolicy: IfNotPresent

  resources:
    limits:
      cpu: 1
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 512Mi
  livenessProbe:
    initialDelaySeconds: 20
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  readinessProbe:
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  terminationGracePeriodSeconds: 10
  ## Creates a custom storage class which can be used in persistence section
  customStorageClass:
      create: false
      name:
      type: pd-standard
      provisioner:
      allowVolumeExpansion: true
      reclaimPolicy: Delete
  maxTriplesToReturn: 50000
  bulkTransactions: true
  # See Apache Jena TDB2 documentation
  storeParams:
    tdb.file_mode: "mapped"
    tdb.block_size: 8192
    tdb.block_read_cache_size: 5000
    tdb.block_write_cache_size: 1000
    tdb.node2nodeid_cache_size: 200000
    tdb.nodeid2node_cache_size: 750000
    tdb.node_miss_cache_size: 1000
    tdb.nodetable: "nodes"
    tdb.triple_index_primary: "SPO"
    tdb.triple_indexes:
      - "SPO"
      - "POS"
      - "OSP"
    tdb.quad_index_primary: "GSPO"
    tdb.quad_indexes:
      - "GSPO"
      - "GPOS"
      - "GOSP"
      - "POSG"
      - "OSPG"
      - "SPOG"
    tdb.prefixtable: "prefixes"
    tdb.prefix_index_primary: "GPU"
    tdb.prefix_indexes:
      - "GPU"
  mail:
    mail.from: info@fairspace.io
    mail.user: user
    mail.password: password
    mail.transport.protocol: smtp
    mail.smtp.auth: true
    mail.smtp.host: host
    mail.smtp.port: 587
    mail.smtp.starttls.enable: true

# Settings for the documentation container
docs:
  nameOverride:
  replicaCount: 1
  image:
    image: eu.gcr.io/fairspace-207108/docs
    tag: RELEASEVERSION
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    externalPort: 80
    internalPort: 8080
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
  probePath: /
  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  readinessProbe:
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  terminationGracePeriodSeconds: 60

# Pod annotations should remain empty. They are filled within the build process
podAnnotations: {}
