# Default values for Fairspace.

# Set specific fairspace name. Defaults to release name
nameOverride:

# External dependencies for running the fairspace
external:
  # Settings for the Keycloak adapter, used to authenticate users and fetch user information.
  keycloak:
    baseUrl:
    loginRealm: fairspace
    realm:
    clientSecret:

# Setup ingress for fairspace components
fairspace:
  name: "fairspace"
  description: "Fairspace"
  ingress:
    enabled: true
    domain:
    annotations:
      pluto:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/proxy-body-size: 10g
        nginx.ingress.kubernetes.io/proxy-read-timeout: "600000"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_set_header  X-Forwarded-Proto $scheme;
      docs:
        kubernetes.io/ingress.class: nginx
    tls:
      enabled: true
      secretNameOverride:
      certificate:
        obtain: true
        issuerRef:
          name: letsencrypt-prod
          kind: ClusterIssuer
  features: []
  services: {}
  storages: {}
  metadata-sources: {}
  icons: {}

# Generic settings for tracing
tracing:
  enabled: false
  samplingRate: 0.1
  baseUrl: http://jaeger-collector.jaeger:9411

#####################################################################
# Specific settings for Saturn subchart
#####################################################################
saturn:
  # loglevel: debug
  auth:
    enableBasicAuth: true
    defaultUserRoles:
      - canViewPublicMetadata
  mvRefreshOnStartRequired: true
  persistence:
    files:
      ## A manually managed Persistent Volume and Claim
      ## If defined, PVC must be created manually before volume will be bound
      # existingClaim:

      ## database data Persistent Volume Storage Class
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
      ##   GKE, AWS & OpenStack)
      ##
      # storageClass: "-"
      size: 50Gi
    database:
      size: 50Gi
    audit:
      size: 5Gi
    extra-file-storage:
  image:
    image: ghcr.io/thehyve/fairspace/saturn
    tag: RELEASEVERSION
    pullPolicy: IfNotPresent
  initContainer:
    image: alpine:3.18
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 1
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 512Mi
  livenessProbe:
    initialDelaySeconds: 20
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  readinessProbe:
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  terminationGracePeriodSeconds: 10
  ## Creates a custom storage class which can be used in persistence section
  customStorageClass:
    create: false
    name:
    type: pd-standard
    provisioner:
    allowVolumeExpansion: true
    reclaimPolicy: Delete
  bulkTransactions: true
  # See Apache Jena TDB2 documentation
  storeParams:
    tdb.file_mode: "mapped"
    tdb.block_size: 8192
    tdb.block_read_cache_size: 5000
    tdb.block_write_cache_size: 1000
    tdb.node2nodeid_cache_size: 200000
    tdb.nodeid2node_cache_size: 750000
    tdb.node_miss_cache_size: 1000
    tdb.nodetable: "nodes"
    tdb.triple_index_primary: "SPO"
    tdb.triple_indexes:
      - "SPO"
      - "POS"
      - "OSP"
    tdb.quad_index_primary: "GSPO"
    tdb.quad_indexes:
      - "GSPO"
      - "GPOS"
      - "GOSP"
      - "POSG"
      - "OSPG"
      - "SPOG"
    tdb.prefixtable: "prefixes"
    tdb.prefix_index_primary: "GPU"
    tdb.prefix_indexes:
      - "GPU"
  vocabulary:
  views:


#####################################################################
# Specific settings for Pluto subchart
#####################################################################
pluto:
  image:
    image: ghcr.io/thehyve/fairspace/pluto
    tag: RELEASEVERSION
    pullPolicy: IfNotPresent
  logLevel: INFO
  resources:
    limits:
      cpu: 1
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 512Mi
  livenessProbe:
    initialDelaySeconds: 20
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  readinessProbe:
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  terminationGracePeriodSeconds: 10
  keycloak:
    redirectAfterLogoutUrl:
  # Gateway timeouts when connecting to upstream services
  responseTimeoutMillis: 600000  # 10 minutes
  connectTimeoutMillis: 2000
  maxFileSize: 1GB    # max total size of file(s) that can be uploaded
  backends:
    storageRoutes:

postgres:
  persistence:
    storage:
      size : 50Gi

# Pod annotations should remain empty. They are filled within the build process
podAnnotations: { }

svgicons: { }