apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-saturn
  labels:
    app: saturn
    {{- include "fairspace.labels" . | nindent 4 }}
data:
  application.yaml: |-
    port: 8090
    publicUrl: https://{{ .Values.fairspace.ingress.domain }}
    jena:
      metadataBaseIRI: http://{{ .Values.fairspace.ingress.domain }}/iri/
      datasetPath: "/data/saturn/db"
      storeParams:
{{ toYaml .Values.saturn.storeParams | indent 8 }}
      transactionLogPath: "/data/saturn/files/log"
      bulkTransactions: {{ .Values.saturn.bulkTransactions }}
    auth:
      authServerUrl: {{ .Values.external.keycloak.baseUrl }}/auth/
      realm: {{ .Values.external.keycloak.realm }}
      clientId: {{ .Values.external.keycloak.clientId }}
      enableBasicAuth: {{ .Values.saturn.auth.enableBasicAuth }}
      superAdminUser: organisation-admin-{{ .Values.external.keycloak.realm }}
    webDAV:
      blobStorePath: "/data/saturn/files/blobs"
    viewDatabase:
      enabled: true
    services:
{{ toYaml .Values.fairspace.services | indent 6 }}
    features:
{{ toYaml .Values.fairspace.features | indent 6 }}
  vocabulary.ttl: |
{{ if .Values.saturn.vocabulary -}}
{{ .Values.saturn.vocabulary | indent 4 -}}
{{ else -}}
{{ .Files.Get "vocabulary.ttl" | indent 4 -}}
{{ end }}
  views.yaml: |
{{ if .Values.saturn.views -}}
{{ .Values.saturn.views | indent 4 -}}
{{ else -}}
{{ .Files.Get "views.yaml" | indent 4 -}}
{{ end }}
