# Hyperspace that this workspace is connected to
hyperspace:
  domain: hyperspace.ci.fairway.app
  keycloak:
    username: keycloak
    password: keycloak-ci-123
    realm: ci
    clientSecret: 4c4e5e3b-a6ed-45fd-a394-46c4f5eea510

# Settings for the workspace
workspace:
  ingress:
    domain: workspace.ci.fairway.app
    tls:
      certificate:
        dns01Provider: gke
  enableExperimentalFeatures: true
  configurationScripts:
    keycloak:
      enabled: true
      pullPolicy: IfNotPresent

pluto:
  image:
    pullPolicy: Always
    
# Specific settings for Saturn subchart
saturn:
  image:
    pullPolicy: Always
  mail:
    mail.from: pavel@thehyve.nl
    mail.user: AKIAISXHGXUIMMU75YVA
    mail.password: Avjpey3XBSvnlPfWGTS2qEjiJykvbDJtj6zWW3fCZILl
    mail.transport.protocol: smtp
    mail.smtp.auth: true
    mail.smtp.host: email-smtp.us-east-1.amazonaws.com
    mail.smtp.port: 587
    mail.smtp.starttls.enable: true


# Specific settings for Mercury subchart
mercury:
  image:
    pullPolicy: Always

# Specific settings for JupyterHub subchart
jupyterhub:
  rbac:
    enabled: true
  auth:
      custom:
          config:
              client_id: workspace-ci-pluto
              client_secret: 4c4e5e3b-a6ed-45fd-a394-46c4f5eea510
              openid_url: https://keycloak.hyperspace.ci.fairway.app/auth/realms/ci/protocol/openid-connect/
              session_url: https://workspace.ci.fairway.app/api/v1/account/tokens
  singleuser:
    image:
      tag: 0.6.1-SNAPSHOT
      pullPolicy: Always
    extraEnv:
      WORKSPACE_URL: https://storage.workspace.ci.fairway.app
  hub:
    image:
      pullPolicy: Always
    extraEnv:
      JUPYTERHUB_CRYPT_KEY: 61efcb6349da848c361e13c0edfac1486d636ef89a2b7cbba610e83d8a332026
  proxy:
      secretToken: "7a437e0359eca81661e82836965bf2b5dc07db4ff10b7686cb18762e601799d9"
