# External dependencies for running the workspace
external:
  keycloak:
    baseUrl: https://keycloak.ci.fairway.app
    username: keycloak
    password: keycloak-ci-123
    realm: ci
    clientId: workspace-ci-pluto
    clientSecret: 4c4e5e3b-a6ed-45fd-a394-46c4f5eea510
  rabbitmq:
    host: hyperspace-ci-rabbitmq.hyperspace-ci.svc.cluster.local
    username: rabbitmq
    password: X6SXtXV3Jzg4gyVR
  elasticsearch:
    enabled: true
    indexName: workspace-ci
    transport:
      host: hyperspace-ci-elasticsearch-discovery.hyperspace-ci.svc.cluster.local
    rest:
      host: hyperspace-ci-elasticsearch-client.hyperspace-ci.svc.cluster.local

# Settings for the workspace
workspace:
  name: "CI Workspace"
  description: "CI Workspace"
  ingress:
    domain: workspace.ci.fairway.app
  enableExperimentalFeatures: true
  configurationScripts:
    keycloak:
      pullPolicy: Always

services:
  jupyterhub: https://jupyter.workspace.ci.fairway.app

pluto:
  image:
    pullPolicy: Always
    tag: 0.6.11-SNAPSHOT
    
# Specific settings for Saturn subchart
saturn:
  image:
    pullPolicy: Always
  customStorageClass:
      create: true
      name: expandable
      type: pd-standard
      provisioner: kubernetes.io/gce-pd
      allowVolumeExpansion: true
  persistence:
    files:
      size: 50Gi
      storageClass: expandable
    database:
      size: 50Gi
      storageClass: expandable
  mail:
    mail.from: pavel@thehyve.nl
    mail.user: AKIAISXHGXUIMMU75YVA
    mail.password: Avjpey3XBSvnlPfWGTS2qEjiJykvbDJtj6zWW3fCZILl
    mail.transport.protocol: smtp
    mail.smtp.auth: true
    mail.smtp.host: email-smtp.us-east-1.amazonaws.com
    mail.smtp.port: 587
    mail.smtp.starttls.enable: true


# Specific settings for Mercury subchart
mercury:
  image:
    pullPolicy: Always

# Specific settings for Mercury subchart
docs:
  image:
    pullPolicy: Always

rabbitmq:
  required: false
  username: workspace-ci
  password: "8VCnaMSHTdcFN9dX"
