# External dependencies for running the fairspace
external:
  keycloak:
    baseUrl: https://keycloak.ci.fairway.app
    realm: ci
    clientId: fairspace-ci-private
    clientSecret: 1877ac71-15ad-4245-bea8-d57c9cbaf3ce

# Settings for fairspace
fairspace:
  name: "CI Fairspace"
  description: "CI Fairspace"
  ingress:
    domain: fairspace.ci.fairway.app
  features: []
  services:
    JupyterHub: https://jupyter.fairspace.ci.fairway.app/user/${username}/lab
  storages:
    test:
      name: test
      label: "Test storage"
      url: https://fairspace.test.fairway.app/api/webdav
      search-url: https://fairspace.test.fairway.app/api/search/files
      root-directory-iri: https://fairspace.test.fairway.app/api/webdav

# Specific settings for Saturn subchart
saturn:
  persistence:
    files:
      size: 60Gi
      storageClass: expandable
    database:
      size: 60Gi
      storageClass: expandable
    audit:
      size: 10Gi
      storageClass: expandable
  resources:
    limits:
      cpu: 1
      memory: 16Gi
    requests:
      cpu: 500m
      memory: 512Mi
  image:
    pullPolicy: Always
  customStorageClass:
    create: true
    name: expandable
    type: pd-standard
    provisioner: kubernetes.io/gce-pd
    allowVolumeExpansion: true

# Specific settings for Pluto subchart
pluto:
  image:
    pullPolicy: Always
  socketTimeoutMillis: 10000
  connectTimeoutMillis: 2000
  maxFileSize: 1GB
  maxRequestSize: 1GB
  backends:
    storageRoutes:
      storage-test-webdav:
        path: /api/storages/test/webdav/**
        url: ${pluto.storages.test.url}
      storage-test-search:
        path: /api/storages/test/search/files/**
        url: ${pluto.storages.test.search-url}
