# Hyperspace that this workspace is connected to
hyperspace:
  domain: hyperspace.test.fairspace.app
  keycloak:
    username: keycloak
    password: yJH7qVjAQ469MVNBR9L5
    realm: test
    clientSecret: db67da94-fa31-47cd-8c42-0ed295790841

# Settings for the workspace
workspace:
  ingress:
    domain: workspace.test.fairspace.app
    tls:
      certificate:
        dns01Provider: gke

# Specific settings for Pluto subchart
pluto:
  keycloak:
    baseUrl: https://keycloak.hyperspace.test.fairspace.app
    realm: test
  tracing:
    enabled: false
  services:
    jupyter: https://jupyterhub.workspace.test.fairspace.app

# Specific settings for Saturn subchart
saturn: {}

mercury: {}

# Specific settings for JupyterHub subchart
jupyterhub:
  rbac:
    enabled: true
  auth:
    custom:
      config:
        client_id: workspace-pluto
        client_secret: db67da94-fa31-47cd-8c42-0ed295790841
        openid_url: https://keycloak.hyperspace.test.fairspace.app/auth/realms/test/protocol/openid-connect/
        session_url: https://workspace.test.fairspace.app/account/tokens
  singleuser:
    image:
      tag: 0.6.0-simple
    extraEnv:
      WORKSPACE_URL: https://storage.workspace.test.fairspace.app
  hub:
    extraEnv:
      JUPYTERHUB_CRYPT_KEY: 8232144c8cba2105c71ee2f0e28158f2cc4417bfd103764017422393619208fe
  proxy:
    secretToken: "a09ebe4bd113e5bded426a1335e3f61f53850a395705563b20115bf717a11c93"
