kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.hyperspace.keycloak.realm }}-organisationadmin
type: Opaque
data:
{{- if .Values.hyperspace.organisationadmin.username }}
  username: {{ .Values.hyperspace.organisationadmin.username | b64enc | quote }}
{{- else }}
  username: {{ printf "organisation-admin-%s" .Values.hyperspace.keycloak.realm | b64enc | quote }}
{{- end }}
{{- if .Values.hyperspace.organisationadmin.password }}
  password: {{ .Values.hyperspace.organisationadmin.password | b64enc | quote }}
{{- else }}
  password: {{ randAlphaNum 10 | b64enc | quote }}
{{- end }}
