apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "pluto.fullname" . }}
  labels:
    app: pluto
    chart: {{ template "workspace.chart" . }}
    draft: {{ default "draft-app" .Values.draft }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.pluto.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.pluto.rollingUpdate.maxSurge | default "25%" }}
      maxUnavailable: {{ .Values.pluto.rollingUpdate.maxUnavailable | default "25%" }}
  selector:
    matchLabels:
      app: pluto
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: pluto
        release: {{ .Release.Name }}
{{- if .Values.pluto.podAnnotations }}
      annotations:
{{ toYaml .Values.pluto.podAnnotations | indent 8 }}
{{- end }}
    spec:
      containers:
      - name: {{ template "pluto.fullname" . }}
        image: "{{ .Values.docker.repository }}/{{ .Values.pluto.image.image }}:{{ .Values.pluto.image.tag }}"
        imagePullPolicy: {{ .Values.pluto.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.pluto.service.internalPort }}
        volumeMounts:
        - name: config-volume
          mountPath: /opt/config
        livenessProbe:
          httpGet:
            path: {{ .Values.pluto.probePath }}
            port: {{ .Values.pluto.service.internalPort }}
          initialDelaySeconds: {{ .Values.pluto.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.pluto.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.pluto.livenessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.pluto.livenessProbe.timeoutSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.pluto.probePath }}
            port: {{ .Values.pluto.service.internalPort }}
          periodSeconds: {{ .Values.pluto.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.pluto.readinessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.pluto.readinessProbe.timeoutSeconds }}
        resources:
{{ toYaml .Values.pluto.resources | indent 12 }}
        env:
        - name: SECURITY_OIDC_CLIENTID
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-oauth-client
              key: clientId
        - name: SECURITY_OIDC_CLIENTSECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-oauth-client
              key: clientSecret
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
      {{- end }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ template "pluto.fullname" . }}
      terminationGracePeriodSeconds: {{ .Values.pluto.terminationGracePeriodSeconds }}
