# Hyperspace that this workspace is connected to
hyperspace:
  domain: hyperspace.ci.test.fairdev.app
  keycloak:
    username: keycloak
    password: keycloak-ci-123
    realm: ci
    clientSecret: 4c4e5e3b-a6ed-45fd-a394-46c4f5eea510

# Settings for the workspace
workspace:
  ingress:
    domain: workspace.ci.test.fairdev.app

pluto:
  keycloak:
    baseUrl: https://keycloak.hyperspace.ci.test.fairdev.app
    realm: ci
  tracing:
    samplingRate: 1

titan:
  auth:
    jwksUrl: https://keycloak.hyperspace.ci.test.fairdev.app/auth/realms/ci/protocol/openid-connect/certs
  tracing:
    samplingRate: 1
  permissions:
    collectionPermissionsUrl: https://workspace.ci.test.fairdev.app/api/collections/permissions?location=%s

# Specific settings for Ceres subchart
ceres:
  app:
    oauth2:
      baseUrl: https://keycloak.hyperspace.ci.test.fairdev.app
      realm: ci
    tracing:
      samplingRate: 1

# Specific settings for Neptune subchart
neptune:
  app:
    oauth2:
      baseUrl: https://keycloak.hyperspace.ci.test.fairdev.app
      realm: ci
    tracing:
      samplingRate: 1
    metadata:
      baseUrl: https://workspace.ci.test.fairdev.app

# Specific settings for JupyterHub subchart
jupyterhub:
    hub:
        extraEnv:
            OAUTH2_AUTHORIZE_URL: https://keycloak.hyperspace.ci.test.fairdev.app/auth/realms/ci/protocol/openid-connect/auth
            OAUTH2_TOKEN_URL: https://keycloak.hyperspace.ci.test.fairdev.app/auth/realms/ci/protocol/openid-connect/certs
        auth:
            type: custom
            custom:
                className: oauthenticator.generic.GenericOAuthenticator
                config:
                    token_url: https://keycloak.hyperspace.ci.test.fairdev.app/auth/realms/ci/protocol/openid-connect/token
                    userdata_url: https://keycloak.hyperspace.ci.test.fairdev.app/auth/realms/ci/protocol/openid-connect/userinfo
                    userdata_method: GET
                    userdata_params: {'state': 'state'}
                    username_key: preferred_username
    proxy:
        secretToken: "7a437e0359eca81661e82836965bf2b5dc07db4ff10b7686cb18762e601799d9"
