{{- $global := . }}
{{- range .Values.saturn.names }}
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ $global.Release.Name }}-saturn-{{.}}
  labels:
    app: saturn
    chart: {{- printf "%s-%s" $global.Chart.Name $global.Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}
    release: {{ $global.Release.Name }}
    heritage: {{ $global.Release.Service }}
spec:
  replicas: {{ $global.Values.saturn.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: {{ $global.Values.saturn.rollingUpdate.maxSurge | default "0%" }}
      maxUnavailable: {{ $global.Values.saturn.rollingUpdate.maxUnavailable | default "100%" }}
  selector:
    matchLabels:
      app: saturn
      release: {{ $global.Release.Name }}
  template:
    metadata:
      labels:
        app: saturn
        release: {{ $global.Release.Name }}
{{- if $global.Values.podAnnotations.saturn }}
      annotations:
{{ toYaml $global.Values.podAnnotations.saturn | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: {{ $global.Release.Name }}-saturn
          image: "{{ $global.Values.saturn.image.image }}:{{ $global.Values.saturn.image.tag }}"
          imagePullPolicy: {{ $global.Values.saturn.image.pullPolicy }}
          ports:
          - containerPort: {{ $global.Values.saturn.service.internalPort }}
          volumeMounts:
          - name: config-volume
            mountPath: /opt/config
          - name: database
            mountPath: /data/saturn/db
          - name: files
            mountPath: /data/saturn/files
          livenessProbe:
            httpGet:
              path: {{ $global.Values.saturn.probePath }}
              port: {{ $global.Values.saturn.service.internalPort }}
            initialDelaySeconds: {{ $global.Values.saturn.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ $global.Values.saturn.livenessProbe.periodSeconds }}
            successThreshold: {{ $global.Values.saturn.livenessProbe.successThreshold }}
            timeoutSeconds: {{ $global.Values.saturn.livenessProbe.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: {{ $global.Values.saturn.probePath }}
              port: {{ $global.Values.saturn.service.internalPort }}
            periodSeconds: {{ $global.Values.saturn.readinessProbe.periodSeconds }}
            successThreshold: {{ $global.Values.saturn.readinessProbe.successThreshold }}
            timeoutSeconds: {{ $global.Values.saturn.readinessProbe.timeoutSeconds }}
          resources:
{{ toYaml $global.Values.saturn.resources | indent 12 }}
    {{- with $global.Values.saturn.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with $global.Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ $global.Release.Name }}-saturn
      - name: database
        {{- if $global.Values.saturn.persistence.database.enabled }}
        persistentVolumeClaim:
          claimName: {{ $global.Release.Name }}-saturn-{{.}}-database
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: files
        {{- if $global.Values.saturn.persistence.files.enabled }}
        persistentVolumeClaim:
          claimName: {{ $global.Release.Name }}-saturn-{{.}}-files
        {{- else }}
        emptyDir: {}
        {{- end }}
{{- end}}