{{- $global := . }}
{{- range $global.Values.saturn.nodes }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $global.Release.Name }}-saturn-{{.name}}-files
  labels:
    app: saturn
    chart: {{ printf "%s-%s" $global.Chart.Name $global.Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    release: {{ $global.Release.Name }}
    heritage: {{ $global.Release.Service }}
{{- if $global.Values.saturn.persistence.files.annotations }}
  annotations:
{{ toYaml $global.Values.saturn.persistence.files.annotations | indent 4 }}
{{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .persistence.files.size | quote }}
{{- if .persistence.files.storageClass }}
  {{- if (eq "-" .persistence.files.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .persistence.files.storageClass | quote }}
  {{- end }}
{{- end }}
