{{- $global := . }}
{{- range .Values.saturn.nodes }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $global.Release.Name }}-saturn-{{.name}}
  labels:
    app: saturn
    chart: {{ printf "%s-%s" $global.Chart.Name $global.Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    release: {{ $global.Release.Name }}
    heritage: {{ $global.Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: saturn
    release: {{ $global.Release.Name }}
{{- end}}
