{{ if .Values.keycloak.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{.Release.Name}}-keycloak-config-map"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
data:
  redirect.urls: |-
    {{ template "workspace.url" . }}/*
{{- end -}}
