# Default values for vre.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Set specific workspace name. Defaults to release name
# Please note that if this is set, also set it for pluto in `pluto.workspace.name`
nameOverride:

# Hyperspace that this workspace is connected to
# Please note that pluto also has to know about the
# keycloak baseUrl and realm, see the pluto configuration
hyperspace:
    tls: true
    domain:
    locationOverrides:
        keycloak:

    # TODO: determine better way to handle keycloak credentials
    # Keycloak credentials are needed to setup the workspace (e.g. users, clients)
    # in keycloak. Please note that this is not a sustainable way of doing, due
    # to the sensitive nature of these parameters
    #
    # We could either:
    # - have the hyperspace setup keycloak itself, when creating a new workspace
    # - use temporary credentials for setting up these users
    # - ...
    keycloak:
        username:
        password:
        realm:
        clientSecret:


# Setup ingress for workspace components
workspace:
    ingress:
        enabled: true
        domain:
        annotations:
            kubernetes.io/ingress.class: nginx
        tls:
            enabled: true
            secretNameOverride:
            certificate:
                obtain: true
                issuerRef:
                    name: letsencrypt-prod
                    kind: ClusterIssuer
                dns01Provider: clouddns

    testuser:
        password: fairspace123
    coordinator:
        password: fairspace123

    # Scripts for setting up keycloak for a workspace
    configurationScripts:
        dockerRepository: docker-registry.jx.test.fairdev.app
        image: fairspace/keycloak-configuration
        configurationScriptsTag: 0.0.25
        pullPolicy: IfNotPresent

# Specific settings for pluto
# Default configuration points to titan, mercury and neptune
# in the same workspace
pluto:
  overrides:
    keycloak:
      client:
        secretNamePostfix: oauth-client

  keycloak:
    baseUrl:
    realm:
    redirectAfterLogoutUrl: https://fairspace.com

  services:
    jupyter:

# Specific settings for JupyterHub subchart
jupyterhub:
    auth:
        type: custom
        custom:
            className: oauthenticator.openid.OpenIDConnectOAuthenticator
            config:
                enable_auth_state: True
                client_id:
                client_secret:
                openid_url:
                session_url:
    singleuser:
      image:
        name: docker-registry.jx.test.fairdev.app/fairspace/jupyterhub-singleuser
        tag: latest
      defaultUrl: "/lab"
      extraEnv:
        WORKSPACE_URL:
    hub:
      image:
        name: docker-registry.jx.test.fairdev.app/fairspace/jupyterhub-hub
        tag: latest
      ingress:
        enabled: false
      extraEnv:
        JUPYTERHUB_CRYPT_KEY:
      extraConfig: |
        c.KubeSpawner.cmd = ['/start']
        c.KubeSpawner.singleuser_privileged = True
        c.Authenticator.auto_login = True
    proxy:
      # The JupyterHub chart requires this value to be set here with the same
      # length as the actual values
      # Ensure to override this value with a 64-character hex string when installing
      secretToken: "0000000000000000000000000000000000000000000000000000000000000000"

# Specific settings for Ceres subchart
ceres:
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 512Mi
      subPath: "ceres-db"
      mountPath: /data/ceres
    app:
      oauth2:
        baseUrl:
        realm:

# Specific settings for Neptune subchart
neptune:
    app:
      oauth2:
        baseUrl:
        realm:
      metadata:
        baseUrl:

# Specific settings for Titan subchart
titan:
    auth:
      tokenUrl:
      clientId:
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 512Mi
      subPath: "titan"
      mountPath: /data

